backend:
  name: github
  repo: totzk9/tribox-gatsby-website
  branch: develop

media_folder: content/assets
public_folder: /assets

collections:
  - name: work
    label: Work
    folder: content/work
    create: true
    path: "{{title}}/index"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: thumbnail, label: Cover Photo, widget: image }
      - { name: description, label: Description, widget: text }
      - { name: client, label: Client }
      - { name: services, label: Services }
      # - { name: featuredOn, label: Featured On, widget: text, required: false }
      - name: "featuredOn"
        label: "Featured On"
        widget: "list"
        summary: '{{fields.featured.name}} - {{fields.featured.link}}'
        required: false
        fields:
          # - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
          - label: Featured
            name: featured
            widget: object
            fields:
              - {label: Name, name: name, widget: string, default: "World Brand Design Society"}
              - {label: Link, name: link, widget: string, required: false }

      - {
          name: isHighlighted,
          label: Is Highlighted,
          widget: boolean,
          default: false,
        }
      - {
          name: isPublishedWork,
          label: Publish Work,
          widget: boolean,
          default: true,
        }
      - { name: body, label: Body, widget: markdown }
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "index"

    fields:
      - { name: date, label: Date, widget: datetime, format: "YYYY-MM-DD", timeFormat: false, pickerUtc: true }
      - { name: title, label: Title }
      - { name: author, label: Author }
      - { name: tags, label: Tags, widget: "list", default: false }
      - {
          name: isPublishedBlog,
          label: Publish Blog,
          widget: boolean,
          default: true,
        }
      - { name: body, label: Body, widget: markdown }
