backend:
  name: github
  repo: totzk9/tribox-gatsby-website

media_folder: content/assets
public_folder: ../assets

collections:
  - name: work
    label: Work
    folder: content/work
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: client, label: Client }
      - { name: services, label: Services, widget: list, default: ["Branding", "Logo"] }
      - { name: problemDescription, label: Problem Description }
      - { name: solutionDescription, label: Solution Description }
      - { name: isHighlighted, label: Is Highlighted, widget: boolean }
      - { name: body, label: Body, widget: markdown }
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }