backend:
  name: github
  repo: totzk9/tribox-gatsby-website
  branch: develop

media_folder: content/assets
public_folder: /assets

collections:
  - name: work
    label: Work
    folder: content/work
    create: true
    path: "{{title}}/index"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: thumbnail, label: Cover Photo, widget: image, hint: "Please provide 2000x1333 resolution for cover photos." }
      - { name: description, label: Description, widget: text }
      - { name: client, label: Client }
      - { name: services, label: Services }
      - name: "featuredOn"
        label: "Featured On"
        widget: "list"
        summary: '{{fields.featured.name}} - {{fields.featured.link}}'
        required: false
        fields:
          - label: Featured
            name: featured
            widget: object
            fields:
              - {label: Name, name: name, widget: string }
              - {label: Link, name: link, widget: string, required: false }
      - {
          name: isHighlighted,
          label: Is Highlighted,
          widget: boolean,
          default: false,
          hint: "Determine to show this Work project in HomePage."
        }
      - {
          name: isPublishedWork,
          label: Publish Work,
          widget: boolean,
          default: true,
          hint: "Determine to publish this on the whole website. Turning this On will create a new site for this Work."
        }
      - { name: body, label: Body, widget: markdown }
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    path: "{{title}}/index"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: category, label: Category, widget: string }
      - { name: thumbnail, label: Cover Photo, widget: image, required: false, hint: "Please provide 2000x1333 resolution for cover photos." }
      - {
          name: isPublishedBlog,
          label: Publish Blog,
          widget: boolean,
          default: true,
        }
      - { name: body, label: Body, widget: markdown }
  - name: news
    label: News
    folder: content/news
    create: true
    path: "{{title}}/index"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: category, label: Category, widget: string }
      - { name: thumbnail, label: Cover Photo, widget: image, required: false, hint: "Please provide 2000x1333 resolution for cover photos." }
      - { name: link, label: Link, widget: string, hint: "Add URL to an external site." }
      - {
          name: isPublishedNews,
          label: Publish News,
          widget: boolean,
          default: true,
        }
